export default function Portfolio() {
    return (
        <div>
            <h2>Portfolio</h2>
            <div>
                <a>
                    <h3></h3>
                    <img></img>
                </a>
            </div>
            <div>
                <a>
                    <h3></h3>
                    <img></img>
                </a>
            </div>
            <div>
                <a>
                    <h3></h3>
                    <img></img>
                </a>
            </div>
            <div>
                <a>
                    <h3></h3>
                    <img></img>
                </a>
            </div>
            <div>
                <a>
                    <h3></h3>
                    <img></img>
                </a>
            </div>
            <div>
                <a>
                    <h3></h3>
                    <img></img>
                </a>
            </div>
        </div>
    );
}